name: Onyo Tests

on:
  [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', 'pypy3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: git config
      run: |
        git config --global user.email "onyo@example.com"
        git config --global user.name "Yoko Onyo"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[tests]"
        sudo apt-get install -y zsh
    - name: flake8 linting
      run: |
        flake8 $(find . -type f -name "*.py")
    - name: Test with pytest and collect coverage
      run: |
        export REPO_ROOT=$PWD
        pytest -vv --cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
