name: Onyo Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Install dependencies
      run: |
        pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest tests/default_tests.py
